show iso url

diff --git a/quickemu-delete b/quickemu-delete
--- a/quickemu-delete
+++ b/quickemu-delete
@@ -15,9 +15,11 @@ if ((selection < 1)) || ((selection > ${#VMs[@]})); then
     echo "Invalid selection. Exiting."
     exit
 fi
+VMDIR=~/Documents/VMs/"${VMs[$selection-1]}"
 read -p 'Are you sure? This will delete the VM. [y/N] ' delinput
 if [[ "${delinput,,}" == "y" ]] || [[ "${delinput,,}"  == "yes" ]]; then
-    rm -rf ~/Documents/VMs/"${VMs[$selection-1]}"
+    cd "$VMDIR" &&
+    quickemu --vm "$(ls | grep .conf)" --delete-vm > /dev/null && rm -rf "$VMDIR" && echo Successfully deleted VM "${VMs[$selection-1]}" || { echo "Failed to delete VM."; exit 1; }
 else
     echo Exiting.
     exit
