Presents information in a better order, more ways to install missing quickemu Also added dependency installation

diff --git a/quickemu-create b/quickemu-create
--- a/quickemu-create
+++ b/quickemu-create
@@ -6,6 +6,22 @@ fullExit() {
   rm -rf "$VMDirectory"/.tmp
   exit
 }
+installQuickemu() {
+	read -p 'Quickemu could not be found. Would you like to install it? [y/n] ' installInput
+	[[ "$installInput" == "y" ]] || [[ "$installInput" == "yes" ]] && {
+		command -v pacman > /dev/null && { command -v yay > /dev/null && yay -Sy quickemu || { echo 'Install quickemu from the AUR instead.'; fullExit; } }
+		cat /proc/version | grep -q Ubuntu && { read -p 'Ubuntu detected. Would you like to install quickemu from the PPA or from Git? (Default: Git) ' UbuntuRepoInput; }
+		if [[ "${UbuntuRepoInput,,}" == "ppa" ]] && sudo apt-add-repository ppa:flexiondotorg/quickemu && sudo apt update && sudo apt -y install quickemu; then
+				echo 'Successfully installed quickemu from PPA.' && sleep 1
+		else
+			[[ "${UbuntuRepoInput,,}" == "ppa" ]] && { echo 'Failed to install quickemu from PPA. Installing from Git instead.'; sleep 1; }
+			git clone https://github.com/quickemu-project/quickemu ~/.local/bin/quickemu 2>&1 > /dev/null && echo Installed quickemu in /home/$(whoami)/.local/bin/quickemu || { echo 'Failed to install quickemu. Exiting.'; fullExit; }
+			echo Attempting to install dependencies; sleep 1
+			command -v apt > /dev/null && sudo apt install qemu bash coreutils ovmf grep jq lsb-base procps python3 genisoimage usbutils util-linux sed spice-client-gtk libtss2-tcti-swtpm0 wget xdg-user-dirs zsync unzip socat
+			command -v dnf > /dev/null && sudo dnf install qemu bash coreutils edk2-tools grep jq lsb procps python3 genisoimage usbutils util-linux sed spice-gtk-tools swtpm wget xdg-user-dirs xrandr unzip
+		fi
+	}
+}
 deleteVMDirectory() {
   rm -rf "$VMDirectory"/"$releaseString"
   fullExit
@@ -74,15 +90,16 @@ customInput() {
 [[ -d ~/.local/bin/quickemu && "$SkipUpdate" != "true" ]] && { git -C ~/.local/bin/quickemu pull 2>&1 | grep -q "changed" && echo Updated quickemu.; } &
 trap fullExit SIGINT
 export PATH=$PATH:~/.local/bin/quickemu
-command -v quickemu > /dev/null || { git clone https://github.com/quickemu-project/quickemu ~/.local/bin/quickemu 2>&1 > /dev/null && echo Installed quickemu in /home/$(whoami)/.local/bin/quickemu; }
+command -v quickemu > /dev/null || installQuickemu
 [ -d "$VMDirectory" ] || { mkdir "$VMDirectory" 2> /dev/null && echo Created VMs folder at "$VMDirectory". || { echo Failed to create VM Folder at "$VMDirectory". Exiting.; fullExit; }; }
 rm -rf "$VMDirectory"/.tmp; mkdir "$VMDirectory"/.tmp
 echo -e 'Available Operating Systems:\n'
 [[ "$WaitForUpdate" == "true" ]] && wait
-echo $(quickget PLACEHOLDER | tail -n +3; echo custom) | tr ' ' '\n' | sort | paste -sd ' ' -
+oslist=$((quickget PLACEHOLDER | tail -n +3; echo custom) | tr ' ' '\n' | sort | paste -sd ' ' -)
+echo $oslist
 read -p $'\nEnter an operating system: ' OS
 OSRemoveSpace=${OS// /}
-
+echo "$oslist" | grep -qw "${OSRemoveSpace,,}" || { echo "${oslist//-/}" | grep -qw "${OSRemoveSpace,,}" && OSRemoveSpace=${OS/ /-}; }
 [[ "${OSRemoveSpace,,}" == "custom" ]] && { customInput && specInput && createCustom && configSpec && startVM; fullExit; }
 
 #Wait for quickemu to finish updating, if applicable. 
@@ -100,7 +117,7 @@ configFile="${OSRemoveSpace,,}-$correctVer${correctEdition:+-$correctEdition}.co
 [[ -d "$VMDirectory"/"$releaseString" ]] && existingVMResponse
 specInput
 mkdir "$VMDirectory"/"$releaseString" && cd "$VMDirectory"/"$releaseString" && trap deleteVMDirectory SIGINT
-quickget ${OSRemoveSpace,,} ${correctVer,,} ${correctEdition:+$correctEdition}
+quickget ${OSRemoveSpace,,} ${correctVer,,} ${correctEdition:+$correctEdition} || { echo 'Could not download OS. Exiting.'; deleteVMDirectory; }
 configSpec
 startVM
 fullExit
